export const DASHBOARD_CONFIG = {
  brand: {
    name: 'StreamVault',
    tagline: 'Premium Entertainment Access',
  },
  colors: {
    primary: 'rgb(54, 235, 138)',
    background: {
      main: '#111111',
      secondary: '#212121',
      tertiary: '#414141',
    },
  },
} as const;

export const pages = [
  { id: 'dashboard', label: 'Dashboard', icon: 'Home' },
  { id: 'offers', label: 'Available Offers', icon: 'Package' },
  { id: 'orders', label: 'Order History', icon: 'ShoppingBag' },
  { id: 'payment', label: 'Payment Methods', icon: 'CreditCard' },
  { id: 'profile', label: 'Profile Settings', icon: 'User' },
] as const;

export const ENTERTAINMENT_OFFERS = [
  {
    id: 1,
    name: 'Netflix Premium Account',
    description: '1-year premium access with 4K streaming',
    icon: '🎬',
    price: 149.99,
    originalPrice: 215.88,
    discount: 30,
    category: 'Streaming',
    features: [
      '4K Ultra HD',
      '4 simultaneous screens',
      'Download content',
      'No ads',
    ],
    validUntil: '2024-12-31',
    color: 'from-red-600 to-red-500',
    popular: true,
  },
  {
    id: 2,
    name: 'Disney+ Bundle Access',
    description: '1-year Disney+ with Hulu and ESPN+',
    icon: '🏰',
    price: 119.99,
    originalPrice: 167.88,
    discount: 25,
    category: 'Streaming',
    features: [
      'Disney+ Premium',
      'Hulu (No Ads)',
      'ESPN+ Access',
      'Family sharing',
    ],
    validUntil: '2024-12-31',
    color: 'from-blue-600 to-blue-500',
    popular: false,
  },
  {
    id: 3,
    name: 'Spotify Premium Family',
    description: '1-year premium music for up to 6 accounts',
    icon: '🎵',
    price: 99.99,
    originalPrice: 179.88,
    discount: 44,
    category: 'Music',
    features: [
      '6 Premium accounts',
      'Ad-free music',
      'Offline downloads',
      'High quality audio',
    ],
    validUntil: '2024-12-31',
    color: 'from-green-600 to-green-500',
    popular: false,
  },
  {
    id: 4,
    name: 'HBO Max Premium',
    description: '1-year premium access with exclusive content',
    icon: '🎭',
    price: 129.99,
    originalPrice: 179.88,
    discount: 28,
    category: 'Streaming',
    features: [
      '4K streaming',
      'Same-day premieres',
      'Max Originals',
      'Ad-free experience',
    ],
    validUntil: '2024-12-31',
    color: 'from-purple-600 to-purple-500',
    popular: false,
  },
  {
    id: 5,
    name: 'YouTube Premium Family',
    description: '1-year ad-free YouTube for 6 members',
    icon: '📺',
    price: 89.99,
    originalPrice: 131.88,
    discount: 32,
    category: 'Video',
    features: [
      'Ad-free videos',
      'Background play',
      'YouTube Music',
      '6 family members',
    ],
    validUntil: '2024-12-31',
    color: 'from-red-500 to-pink-500',
    popular: false,
  },
  {
    id: 6,
    name: 'Gaming Bundle Pack',
    description: 'Xbox Game Pass Ultimate + PlayStation Plus',
    icon: '🎮',
    price: 199.99,
    originalPrice: 299.88,
    discount: 33,
    category: 'Gaming',
    features: [
      'Xbox Game Pass Ultimate',
      'PlayStation Plus Premium',
      'Cloud gaming',
      '100+ games',
    ],
    validUntil: '2024-12-31',
    color: 'from-indigo-600 to-purple-600',
    popular: true,
  },
] as const;

export const ORDER_HISTORY = [
  {
    id: 'ORD-2024-001',
    date: '2024-11-28',
    service: 'Netflix Premium Account',
    amount: 149.99,
    status: 'delivered' as const,
    category: 'Streaming',
    accountDetails: {
      email: 'netflix.***@streamvault.com',
      password: '***********',
      expiresOn: '2025-11-28',
    },
  },
  {
    id: 'ORD-2024-002',
    date: '2024-11-22',
    service: 'Spotify Premium Family',
    amount: 99.99,
    status: 'delivered' as const,
    category: 'Music',
    accountDetails: {
      email: 'spotify.***@streamvault.com',
      password: '***********',
      expiresOn: '2025-11-22',
    },
  },
  {
    id: 'ORD-2024-003',
    date: '2024-11-15',
    service: 'Disney+ Bundle Access',
    amount: 119.99,
    status: 'delivered' as const,
    category: 'Streaming',
    accountDetails: {
      email: 'disney.***@streamvault.com',
      password: '***********',
      expiresOn: '2025-11-15',
    },
  },
  {
    id: 'ORD-2024-004',
    date: '2024-11-10',
    service: 'HBO Max Premium',
    amount: 129.99,
    status: 'processing' as const,
    category: 'Streaming',
    accountDetails: null,
  },
  {
    id: 'ORD-2024-005',
    date: '2024-10-28',
    service: 'YouTube Premium Family',
    amount: 89.99,
    status: 'delivered' as const,
    category: 'Video',
    accountDetails: {
      email: 'youtube.***@streamvault.com',
      password: '***********',
      expiresOn: '2025-10-28',
    },
  },
] as const;

export const PAYMENT_METHODS = [
  {
    id: 1,
    type: 'Visa' as const,
    last4: '4242',
    expiry: '05/25',
    isDefault: true,
    holderName: 'John Doe',
  },
  {
    id: 2,
    type: 'Mastercard' as const,
    last4: '8353',
    expiry: '09/24',
    isDefault: false,
    holderName: 'John Doe',
  },
] as const;

export const USER_PROFILE = {
  name: 'John Doe',
  email: 'john.doe@example.com',
  phone: '(555) 123-4567',
  memberSince: '2023-01-15',
  totalOrders: 12,
  totalSpent: 1247.89,
  loyaltyPoints: 750,
  avatar: '/placeholder.svg?height=96&width=96',
} as const;

export const PROMOTIONAL_OFFERS = [
  {
    id: 1,
    title: 'Black Friday Mega Bundle',
    description: 'Get Netflix + Disney+ + Spotify for one low price',
    discount: 'Save $150',
    originalPrice: 449.97,
    salePrice: 299.99,
    expires: '2024-12-01',
    color: 'from-purple-600 to-pink-600',
    featured: true,
  },
  {
    id: 2,
    title: 'Gaming Ultimate Pack',
    description: 'Xbox Game Pass + PlayStation Plus + Steam Credits',
    discount: 'Save $100',
    originalPrice: 399.99,
    salePrice: 299.99,
    expires: '2024-12-15',
    color: 'from-blue-600 to-cyan-500',
    featured: false,
  },
] as const;

export const DASHBOARD_STATS = {
  totalPurchases: 12,
  totalSpent: 1247.89,
  activePurchases: 8,
  savedAmount: 324.5,
} as const;
